PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>

SELECT ?snp ?trait_type ?trait_name
WHERE {
  ?gwas_assoc a biolink:Association ;
              biolink:has_subject ?snp ;
              biolink:has_object ?trait .

  ?trait a ?trait_type ;
         rdfs:label ?trait_name .
}
